### ISSUE TITLE
GuideBot & Misaki Clone

### ISSUE THREAD

**Issue by YorkAARGH** [DS-Development/delet#134]
As far as I'm aware, you legally cannot change the copyright from one project to another, this project is clearly a copy of GuideBot by myself and my administrator.

At the very least, please give _An Idiot's Guide_ the correct credit it should receive.

On closer inspection it also appears that you have cloned aspects and parts of my personal bot Misaki.

Please accredit the files / code you have taken with the correct MIT license.

**Comment by eslachance** [comment]
"We're big fans of open-source here at DS Development. delet is an open-source project; which is why it can be found here, on GitHub."
But you have no problem stealing code from other people and not giving them credits? You know that's literally illegal, right?

**Comment by suvanl** [comment]
This was originally created as an extension of GuideBot's code, which I used as a base for this version of my bot, as it also contains a number of files which aren't part of/based on GuideBot/Misaki.

However, I'm happy to make changes to give full credit in the appropriate places, and I will update the files which are based on Misaki to give such credit in all places.

Unfortunately, I was unaware of the legal implications of the situation, as I had misunderstood the terms of the license. I'm incredibly sorry that this has happened, and I'll ensure it does not happen again. I hope this resolves the issue.

**Comment by YorkAARGH** [comment]
If the code was moderately modified, then you wouldn't need to apply any such licenses, but since these are basically copy/paste versions of the files, the licensing needs to be applied.

as long as a license header is included in each file from guidebot / misaki, then the issue will be resolved.

**Comment by suvanl** [comment]
Understood, I will be modifying the files in the near future to avoid these sorts of issues from arising.
For now, I'll add license headers stating where they are from, as well as the license of the project they're from.

**Comment by YorkAARGH** [comment]
Sorry, I was made aware that my language was a bit vague

I didn't mean the entire copyright license at the top of each file, just something like

`// Copyright (c) 2019 An Idiot's Guide. All rights reserved. MIT license.`

Would be perfectly acceptable.

**Comment by eslachance** [comment]
IMHO, if you're "big fans" of open source, you should also considering adding a second line that links to the repository itself, as a second line to that header. (both repositories, depending on the file you're in).

**Comment by suvanl** [comment]
Ahh alright. So should I only add this to the main `index.js` file (as that's where the current copyright header is)?

We'll also add the second line you mentioned.

**Comment by eslachance** [comment]
To help distinguish what's "your code" and what's "other code", ideally you'd add that 2-line header to each file that's coming from another repository. I expect that's the vast majority of the files in your initial commit here: https://github.com/DS-Development/delet/tree/f3b0142e80ea3f745fba9e291eb008a760060aec

**Comment by suvanl** [comment]
Made the changes in this commit: https://github.com/DS-Development/delet/commit/d9ff529131e1c582787dc7ed7f5abfa0b9aae426.
Would this be fine?

**Comment by eslachance** [comment]
That looks very good to me!

**Comment by suvanl** [comment]
Great, thanks! Once again, apologies for the original issue.
