### ISSUE TITLE
addcmd/delcmd/ecmd/dcmd

### ISSUE THREAD

**Issue by oodvg** [DS-Development/delet#252]
[feature] able to add/delete custom commands to a single guild and not all.
example, /addcmd [custom command name] [response] [what permlevel]

[feature2] able to enable, disable commands to a single guild and not all
example, /ecmd ping.
the bot shall replay enabled command **ping**
if the command is disabled, the bot shall reply "This command is disabled by the server admins!"

**Comment by suvanl** [comment]
Will be considered for delet<sup>3</sup>. See https://github.com/DS-Development/delet/issues/253#issuecomment-619054867 for more info.
