### ISSUE TITLE
Leveling/Money/Shop System

### ISSUE THREAD

**Issue by oodvg** [DS-Development/delet#253]
[feature] Guild leveling system
a file where each level (xp) is worth.
you get random amount of xp between 25-50
with /work to get money for the shop. the shop, you can buy custom roles and more xp
/xp to get your profile xp.
/leaderboard to get the server top 10.
/daily to get 50 bot bucks and a random amount of xp under 300
when you first join the server, you start with 0 xp with level 0.
level 1 = 1000
level 2 = 2000
level 3 = 3500
level 4 = 7000 etc...

**Comment by suvanl** [comment]
Hi, thanks a lot for submitting these feature requests!

As stated in https://github.com/DS-Development/delet/issues/250#issuecomment-608144119, this version of delet will no longer be updated, and will soon be deprecated* in favour of delet 3.0.0 (delet<sup>3</sup>), which is currently in development and exists in a different repository.

That said, your feature requests do seem interesting and will be taken into consideration for delet<sup>3</sup>.


<sub>*I'll probably be archiving this repository soon</sub>

edit: I should also mention that a points system is already in the works for the next version of the bot, so these suggestions are useful.

**Comment by oodvg** [comment]
adding on to the leveling system.
level 0 = 0 xp
level 1          ::  1000 xp
level 2          ::  2000 xp
level 3          ::  3500 xp
level 4          ::  7000 xp
level 5          ::  14000 xp
level             ::  25000 xp
level 7          ::  50000 xp
level 8          ::  80000 xp
level 9          ::  125000 xp
level 10        ::  175000 xp

also, i dont have a problem with modifying what is above i would just think it would be a challenge with the levels :)

**Comment by suvanl** [comment]
This seems like a good starting point - however, I think it'd be best if users (server admins) were allowed to determine their own level structure for their server. For example, a setting could be implemented (something like `levelsInterval`), which would allow users to specify their own set interval between levels. 

Alternatively, to increase the difficulty as a user goes up the ladder of levels, the square of the last interval could be used for each level. For example:
- level 1: 10pts
- level 2: 100pts
- level 3: 10000pts

and so on...

However, the above idea could lead to ridiculous amounts of points being required for certain levels, so I'll look into this idea and formulate a plan sometime soon.
