### ISSUE TITLE
updated mute

### ISSUE THREAD

**Issue by oodvg** [DS-Development/delet#265]
sorry for more suggestions

anyways, an updated mute command. i noticed with this verison of delet, all mutes are perm until moderator unmutes.
however, delet3 should have a updated mute command.
example, [prefix]mute @user [reason], you shouldnt have to add a time limit as the bot does that for you!
the bot should reply, How long do you want to mute [user] for?
[A] : 1 hour
[B] : 1 day
[C] : 7 days
[D] : Custom
bot reacts to A, B, C, or D.
user [server moderators] reacts to anyone they would like.
if moderator reacts to [D] Custom, bot replys Please specify a time to mute this user for. Examples: 10 minutes, 3 days, 1 month.
example with what i came up with is down below 
![example](https://user-images.githubusercontent.com/55554025/81219888-73e9b900-8fae-11ea-9f49-025e44e96bd2.PNG)

i thought this would be a great idea for delet3 as well as more verisons of delet to come!

**Comment by oodvg** [comment]
i just did this is some friends so i thought it would make a great suggestion.

**Comment by suvanl** [comment]
This seems like a great idea! The moderation commands for delet3 haven't been written yet, so I'll definitely be taking this suggestion into consideration when doing so.

> you shouldnt have to add a time limit as the bot does that for you

I think the mute process would be more streamlined if it was possible to (optionally) specify the duration as a parameter when running the command, and if no duration is specified, a prompt (like the one you've shown) comes up.
